# Generated by Django 5.1.1 on 2024-09-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
