# Generated by Django 5.1.1 on 2024-10-09 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0002_alter_orderitem_product'),
        ('shop', '0008_comment_remove_product_category_delete_commande_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='shop.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
